import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#009668',
        'tertiary-container': '#002113',
        'outline': '#76777d',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#ffb86f',
        'on-primary-fixed-variant': '#3f465c',
        'primary': '#000000',
        'surface-container': '#eceef0',
        'secondary': '#8a5100',
        'on-surface': '#191c1e',
        'secondary-container': '#fe9800',
        'on-primary-fixed': '#131b2e',
        'on-tertiary-fixed-variant': '#005236',
        'surface-variant': '#e0e3e5',
        'on-surface-variant': '#45464d',
        'surface-container-high': '#e6e8ea',
        'inverse-on-surface': '#eff1f3',
        'outline-variant': '#c6c6cd',
        'on-background': '#191c1e',
        'tertiary-fixed': '#6ffbbe',
        'error': '#ba1a1a',
        'surface-dim': '#d8dadc',
        'on-secondary-fixed': '#2c1600',
        'on-secondary-fixed-variant': '#693c00',
        'surface': '#f7f9fb',
        'tertiary-fixed-dim': '#4edea3',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#002113',
        'on-primary-container': '#7c839b',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#dae2fd',
        'surface-container-highest': '#e0e3e5',
        'primary-container': '#131b2e',
        'on-secondary-container': '#643900',
        'inverse-primary': '#bec6e0',
        'background': '#f7f9fb',
        'on-error': '#ffffff',
        'surface-tint': '#565e74',
        'tertiary': '#000000',
        'secondary-fixed': '#ffdcbd',
        'primary-fixed-dim': '#bec6e0',
        'on-secondary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '1rem',
        'stack-md': '1rem',
        'gutter': '1.5rem',
        'container-max': '1440px',
        'stack-lg': '2rem',
        'margin-desktop': '2.5rem',
        'stack-sm': '0.5rem',
      },
      fontFamily: {
        'data-mono': ['Geist', 'monospace'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-score': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-score': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}

export default config
