version = 0.1

[default.global.parameters]
stack_name = "serverless-scanner"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false

[default.deploy.parameters]
region = "us-east-1"
